services:
  gifts_system:
    container_name: gifts_system
    build:
      context: .
      dockerfile: gifts_system/Dockerfile
    volumes:
      - ./gifts_system:/app
      - ./database:/database
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app:/database
    restart: always

  tg_bot:
    container_name: aiogram_bot
    build:
      context: .
      dockerfile: tg_bot/Dockerfile
    volumes:
      - ./tg_bot:/app
      - ./database:/database
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app:/database
    depends_on:
      - gifts_system
    restart: always
